### ISSUE TITLE
Add members information

### ISSUE THREAD

**Issue by romsto** [ldilab/ldilab.github.io#2]
Fill in the members information. Every one should make his/her own member card.
To do so please:
- create a Markdown file under `_members/`
- don't forget to add a profile picture under `_assets/images/people/`

### From Readme

Under `_members/`, each member is represented through a markdown file.
Please adopt the filename as follow: `<family name lowercased><first letters of each symbol>.md`

Content:
```yaml
---
short_name: <filename>
name: Family First
korean_name: 
position: <M.S. Student | Ph.D. & M.S. (integrated) Student | Ph.D. Student | Professor> (Please respect the exact format)
department: Department of Computer Science and Engineering
interests:
 - "Interest 1"
 - "Interest 2"
education:
 - Please always use <Type (M.S. | Ph.D. | B.S.)> in <Field>, <University> <Year> format. From most recent to oldest.
mail: <your mail>
website: [Optional] <your website>
office: <your office>
photo: <file name with extension under _assets/images/people>
---
[Optional] Biography or whatever you want in the markdown format
```

Don't forget to add the photo under `_assets/images/people/`.
